using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace SourceGenerators.Generator;

[Generator]
public class ToStringGenerator : IIncrementalGenerator
{
    private const string AttributeName = "GenerateToStringAttribute";

    private const string AttributeSource = @"// <auto-generated/>
namespace SourceGenerators;

[System.AttributeUsage(System.AttributeTargets.Class | System.AttributeTargets.Struct)]
internal sealed class GenerateToStringAttribute : System.Attribute { }
";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Always emit the marker attribute.
        context.RegisterPostInitializationOutput(ctx =>
            ctx.AddSource("GenerateToStringAttribute.g.cs",
                SourceText.From(AttributeSource, Encoding.UTF8)));

        // Find all class/struct declarations decorated with [GenerateToString].
        var targets = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                $"SourceGenerators.{AttributeName}",
                predicate: static (node, _) => node is ClassDeclarationSyntax or StructDeclarationSyntax,
                transform: static (ctx, _) => GetTypeInfo(ctx))
            .Collect();

        context.RegisterSourceOutput(targets, Execute);
    }

    private static TypeInfo GetTypeInfo(GeneratorAttributeSyntaxContext ctx)
    {
        var typeSymbol = (INamedTypeSymbol)ctx.TargetSymbol;

        var properties = typeSymbol.GetMembers()
            .OfType<IPropertySymbol>()
            .Where(p => p.DeclaredAccessibility == Accessibility.Public && !p.IsStatic && p.GetMethod != null)
            .Select(p => p.Name)
            .ToImmutableArray();

        var ns = typeSymbol.ContainingNamespace.IsGlobalNamespace
            ? null
            : typeSymbol.ContainingNamespace.ToDisplayString();

        return new TypeInfo(ns, typeSymbol.Name, typeSymbol.IsValueType, properties);
    }

    private static void Execute(SourceProductionContext ctx, ImmutableArray<TypeInfo> types)
    {
        foreach (var type in types)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");

            if (type.Namespace != null)
            {
                sb.AppendLine($"namespace {type.Namespace};");
                sb.AppendLine();
            }

            var keyword = type.IsValueType ? "struct" : "class";
            sb.AppendLine($"partial {keyword} {type.TypeName}");
            sb.AppendLine("{");

            // Build the interpolated string parts.
            if (type.Properties.Length == 0)
            {
                sb.AppendLine($"    public override string ToString() => \"{type.TypeName} {{ }}\";");
            }
            else
            {
                var parts = string.Join(", ",
                    type.Properties.Select(p => $"{p} = {{{p}}}"));
                sb.AppendLine($"    public override string ToString() => $\"{type.TypeName} {{{{ {parts} }}}}\";");
            }

            sb.AppendLine("}");

            var hint = type.Namespace != null
                ? $"{type.Namespace}.{type.TypeName}.g.cs"
                : $"{type.TypeName}.g.cs";

            ctx.AddSource(hint, SourceText.From(sb.ToString(), Encoding.UTF8));
        }
    }

    private sealed class TypeInfo
    {
        public string Namespace { get; }
        public string TypeName { get; }
        public bool IsValueType { get; }
        public ImmutableArray<string> Properties { get; }

        public TypeInfo(string ns, string typeName, bool isValueType, ImmutableArray<string> properties)
        {
            Namespace = ns;
            TypeName = typeName;
            IsValueType = isValueType;
            Properties = properties;
        }
    }
}
